# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
 - group: Deploy-Info

stages:
- stage: Build
  jobs:
     - job: Build_ARM
       pool:
          vmImage: ubuntu-latest
       steps:
        - task: Armory@2
          inputs:
            toolVersion: 'LatestPreRelease'
            targetDirectory: '$(Build.SourcesDirectory)'
            targetFiles: 'f|**\*.json;-|.gdn\**;'
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: $(AzureResourceManagerConnection)
            subscriptionId: $(Subscription)
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'demo-arm-rg'
            location: 'East US 2'
            templateLocation: 'Linked artifact'
            csmFile: 'azuredeploy.json'
            overrideParameters: '-projectName demoarm'
            deploymentMode: Validation


- stage: Deploy
  dependsOn: Build
  jobs:
     - deployment: deploy_ARM
       environment: 'development'
       pool:
          vmImage: vs2017-win2016
       strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - download: none
              - task: AzureResourceManagerTemplateDeployment@3
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: $(AzureResourceManagerConnection)
                  subscriptionId: $(Subscription)
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'demo-arm-rg'
                  location: 'East US 2'
                  templateLocation: 'Linked artifact'
                  csmFile: 'azuredeploy.json'
                  overrideParameters: '-projectName demoarm'
                  deploymentMode: Incremental